export interface OnePunchManTags {
  // sex: string;
  // description: string;
  abilities: string;
  affiliation: string;
  age: string;
  alias: string;
  class: string;
  description: string;
  gallery: string;
  height: string;
  location: string;

  // titles: string;
  name: string;
  occupation: string;
  partner: string;
  photo: string;
  race: string;
  rank: string;
  sex: string;
  status: string;
  weight: string;
  // birthday: string;
  // status: string;
  // age: string;
  // height: string;
  // weight: string;
  // classification: string;
  // team: string;
  // partner: string;
  // occupation: string;
  // ninja_rank: string;
  // ninja_registration: string;
  // family: string;
  // jutsu: string;
  // nature_type: string;
  // tools: string;
  // quotes: string;
  // manga: string;
  // anime: string;
  // movie: string;
  // novel: string;
  // game: string;
  // ova: string;
  // voices: {
  //     name: string;
  //     country: string;
  // };
  // kekkei_genkai: string;
  // affiliation: string;
  // clan: string;
}
