export enum TagsPtBr {
  Name = '.page-header__title',
  Description = '#mw-content-text > aside ~ p',
  Photo = "[data-source='Imagem'] > div figure a",
  Titles = "[data-source='Nome'] > div > i",
  Age = "[data-source='IdadeI'] > div",
  Height = "[data-source='AlturaI'] > div",
  Weight = "[data-source='PesoI'] > div",
  Classification = "[data-source='Classificação'] > div > a",
  Team = "[data-source='Times'] > div > a",
  Partner = "[data-source='Parceiro'] > div > a",
  Occupation = "[data-source='Ocupação'] > div > a",
  NinjaRank = "[data-source='Patente NinjaI'] > div > a",
  NinjaRegistration = "[data-source='Registro Ninja'] > div",
  Family = "[data-source='Família'] > div > div > .NavContent > p > a",
  Jutsu = ".tabbertab[title='Mangá'] > div > table > tbody > tr",
  NatureType = "[data-source='Chakra'] > div > div > .NavContent > p > a",
  Tools = '.lua > tbody > tr',
  Quotes = '.lua > tbody > tr',
  Birthday = '[data-source=Aniversário] > div',
  Status = '[data-source=Estado] > div',
  Sex = '[data-source=Sexo] > div > a:nth-child(2)',
  Manga = '[data-source=Mangá] > div > a',
  Anime = '[data-source=Anime] > div',
  Novel = '[data-source=Novela] > div',
  Movie = '[data-source=Filme] > div > i > a',
  Game = '[data-source=Game] > div > i > a',
  Ova = '[data-source=Ova] > div > i > a',
  Clan = "[data-source='Clã'] > div > a",
  Affiliation = "[data-source='Afiliação'] > div > a",
  KekkeiGenkai = "[data-source='Kekkei Genkai'] > div > a",
  VoicesName = '[data-source=Japonês] > div|[data-source=Português] > div',
  VoicesCountry = '[data-source=Japonês] > h3 > small > b|[data-source=Português] > h3 > small > b',
}

export enum TagsEn {
  Name = '',
  Description = '',
  Photo = '',
  Titles = '',
  Age = '',
  Height = '',
  Weight = '',
  Classification = '',
  Team = '',
  Partner = '',
  Occupation = '',
  NinjaRank = '',
  NinjaRegistration = '',
  Family = '',
  Jutsu = '',
  NatureType = '',
  Tools = '',
  Quotes = '',
  Birthday = '',
  Status = '',
  Sex = '',
  Manga = '',
  Anime = '',
  Novel = '',
  Movie = '',
  Game = '',
  Ova = '',
  Clan = '',
  Affiliation = '',
  KekkeiGenkai = '',
  VoicesName = '',
  VoicesCountry = '',
}

export enum TagsEs {
  Name = '.page-header__title',
  Description = '#mw-content-text > aside ~ p',
  Photo = '.pi-image-collection > div figure a',
  Titles = "[data-source='Sobrenombre'] > div > i",
  Age = "[data-source='Edad'] > div",
  Height = "[data-source='Altura'] > div",
  Weight = "[data-source='Peso'] > div",
  Classification = "[data-source='Clasificacion'] > div > a",
  Team = "[data-source='Equipo'] > div > a",
  Partner = "[data-source='Compañero'] > div > a",
  Occupation = "[data-source='Ocupacion'] div > a",
  NinjaRank = "[data-source='Rango'] div > a",
  NinjaRegistration = "[data-source='Registro'] > div",
  Family = "[data-source='Família'] > div > a",
  Jutsu = "[data-source='Jutsus'] > div > a",
  NatureType = "[data-source='Elemento'] > div > a",
  Tools = "[data-source='Armas'] > div > a",
  Quotes = '#mw-content-text > ul',
  Birthday = '[data-source=Nacimiento] > div',
  Status = '[data-source=Nacimiento] ~ div:nth-of-type(3) > div',
  Sex = '[data-source=Nacimiento] ~ div:nth-of-type(2) > div > a:nth-child(2)',
  Manga = '[data-source=Debutmanga] > div > a',
  Anime = '[data-source=Debutanime] > div > a',
  Novel = '[data-source=Debutnovela] > div > a',
  Movie = '[data-source=Debutpelicula] > div > a',
  Game = '[data-source=Debutjuego] > div > a',
  Ova = '[data-source=Debutova] > div > a',
  Clan = "[data-source='Clan'] > div > a",
  Affiliation = "[data-source='Afiliacion'] > div > a",
  KekkeiGenkai = "[data-source='Kekkeigenkai'] > div > a",
  VoicesName = '[data-source=Seiyū] > div|[data-source=Españollatino] > div|[data-source=Españolespaña] > div',
  VoicesCountry = '[data-source=Seiyū] > h3|[data-source=Españollatino] > h3|[data-source=Españolespaña] > h3',
}
